name: CI Ubuntu Codecoverage

# Set QT_QPA_PLATFORM for headless testing
#
env:
  QT_VERSION:      "5.15.2"
  QT_QPA_PLATFORM: "offscreen"
  
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '.github/workflows/**'
      - 'README.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:       
    - name: Dependencies
      run: |
           sudo apt-get update
           sudo apt-get install -y libsamplerate-dev
           sudo apt-get install -y fftw3-dev
           sudo apt-get install -y alsa-base
           sudo apt-get install -y dssi-dev
           sudo apt-get install -y ladspa-sdk
           sudo apt-get install -y libjack-dev
           sudo apt-get install -y liblo-dev
           sudo apt-get install -y liblrdf-dev
           sudo apt-get install -y gcovr

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: ${{ env.QT_VERSION }}

    - uses: actions/checkout@v3

    - name: Tests
      run: |
        export MAKEFLAGS="-j `nproc`"
        mkdir build-test
        cd build-test
        echo "Building and Running tests"
        cmake .. -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTING=ON
        make
        make test
         
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        gcov: true