name: CI Mac

env:
  QT_VERSION:     "5.15.2"
  
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '.github/workflows/**'

jobs:
  build:
    runs-on: macos-12
    
    steps:       
    - name: Dependencies
      run: |
           brew update
           brew install libsamplerate
           brew install fftw
           brew install jack
           brew install liblo
           brew install lrdf

    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: ${{ env.QT_VERSION }}

    - uses: actions/checkout@v1
        
    - name: Configure & Build
      run: |
           ls
           export MAKEFLAGS="-j `nproc`"
           mkdir build
           cd build
           echo "Running cmake"
           cmake .. -DCMAKE_BUILD_TYPE=Debug
           echo "Building"
           make
           
           
           


