name: CI Mac

env:
  QT_VERSION:     "5.15.2"
  
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '.github/workflows/**'
      - 'README.*'

jobs:
  build:
    runs-on: macos-12
    
    steps:       
    - name: Dependencies
      run: |
           brew update
           brew install libsamplerate
           brew install fftw
           brew install jack
           brew install lrdf

    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: ${{ env.QT_VERSION }}

    - uses: actions/checkout@v1

    - name: LADSPA and DSSI install
      run:
          curl https://www.ladspa.org/ladspa_sdk/ladspa.h.txt > src/sound/ladspa.h
          curl https://dssi.sourceforge.net/dssi.h.txt > src/sound/dssi.h

    - name: Liblo needs building
      run: 
          git clone git://liblo.git.sourceforge.net/gitroot/liblo/liblo
          cd liblo
          mkdir cmake-build
          cd cmake-build
          cmake ../cmake
          make
          sudo make install

        
    - name: Configure & Build
      run: |
           export MAKEFLAGS="-j `sysctl -n hw.ncpu`"
           mkdir build
           cd build
           echo "Running cmake"
           cmake .. -DCMAKE_BUILD_TYPE=Debug
           echo "Building"
           make
           
           
           


